//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeHub.Models.GeneratedClassesByEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Table
    {
        public int Login_ID { get; set; }
        public int Viewer_ID { get; set; }
        public int Presenter_ID { get; set; }
        public string Login_Password { get; set; }
    
        public virtual Viewer_Table Viewer_Table { get; set; }
        public virtual Presenter_Table Presenter_Table { get; set; }
    }
}
