//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeHub.Models.GeneratedClassesByEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegisteredCours
    {
        public int Id { get; set; }
        public int viewer_courseid { get; set; }
        public string viewer_coursename { get; set; }
        public Nullable<int> viewer_id { get; set; }
    
        public virtual Viewer_Table Viewer_Table { get; set; }
    }
}
