//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeHub.Models.GeneratedClassesByEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegisteredCours
    {
        public int Id { get; set; }
        public int viewer_courseid { get; set; }
        public string viewer_coursename { get; set; }
        public int viewer_id { get; set; }
        public int teacher_id { get; set; }
        public string teacher_name { get; set; }
        public string timing { get; set; }
        public string days { get; set; }
        public string viewer_name { get; set; }
    }
}
