//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeHub.Models.GeneratedClassesByEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherRegisteredCours
    {
        public int id { get; set; }
        public string CourseName { get; set; }
        public string TeacherName { get; set; }
        public string TeacherId { get; set; }
        public string Timing { get; set; }
        public string Days { get; set; }
    }
}
