//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KnowledgeHub.Models.GeneratedClassesByEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewer_Table
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Viewer_Table()
        {
            this.Login_Table = new HashSet<Login_Table>();
        }
    
        public int Viewer_ID { get; set; }
        public string Viewer_Name { get; set; }
        public string Viewer_City { get; set; }
        public string Viewer_Email { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public string Viewer_Ph_Num { get; set; }
        public string Viewer_Gender { get; set; }
        public Nullable<System.DateTime> Viewer_Login_Date_Time { get; set; }
        public Nullable<System.DateTime> Viewer_Logout_Date_Time { get; set; }
        public byte[] Viewer_image { get; set; }
        public string DOB_Days { get; set; }
        public string DOB_Months { get; set; }
        public string DOB_Year { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Login_Table> Login_Table { get; set; }
    }
}
